name: C2VN Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 3838
          script: |
            cd /home/tung/c2vn.io
            source ~/.bashrc   # load fnm và PATH của user tung
            git fetch origin
            git checkout production
            git pull
            npm install
            npm run build
            pm2 reload c2vn
